- setup.py
When setting the environment variable THREADING_BACKEND to gevent, web3 uses
gevent. This prevents installation if gevent isn't installed.
So, let's clear the environment variable at the top of setup.py.
> make installation work even if THREADING_BACKEND is set

- contracts/CurrencyNetwork.sol
changed the feedivisor from internal to public in order to be able to read it on the relay server and use the proper fee parameter.
> changed the feedivisor from internal to public

- contracts/CurrencyNetwork.sol
This adds natspecs only for the public functions. I would have felt bad when
only documenting the new private functions, and was to lazy to document all
private functions.
see https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format
for a description.
see https://github.com/trustlines-network/contracts/issues/142
> add natspecs for the new functions used for closing trustlines

- .gitignore
- contracts/CurrencyNetwork.sol
- tests/test_currency_network_fees.py
- tests/test_currency_network_interests.py
- tests/test_currency_network_receiver_pays.py
As decided we remove the fees for the last hop, as the receiver should
not receive a fee additional to the amount he already receives.
Closes #154 
Remove the fees for the first hop if the receiver pays in alignment
to removing the fees for the last hop if the sender pays.
Closes #155
Also make transferReceiverPays function public available so that also
other users can use it.
Closes #140
> Remove fees on first and last hop

- contracts/CurrencyNetwork.sol
- tests/test_currency_network_basics.py
- tests/test_gas_costs.py
Rename updateTrustline to updateCreditlimits for function without
interests. We had two functions before with the same name updateTrustlines
which causes problems in some libraries, for example the lightwallet lib we
used, because they do not handle that case properly.
Fixes #150
> Rename updateTrustline to updateCreditlimits

- .pre-commit-config.yaml
- .soliumignore
- constraints.txt
- contracts/TestCurrencyNetwork.sol
- py-deploy/setup.py
- py-deploy/tldeploy/cli.py
- py-deploy/tldeploy/core.py
This commit adds a TestCurrencyNetwork contract that subclasses the
CurrencyNetwork contract. It provides additional methods that can be used to
call into internal functions of CurrencyNetwork.
It should only be used for development and testing. It could be used to test
internal functions or export test data for the corresponding python
implementation of these internal functions.
The tldeploy.core.deploy_network functions takes an additional parameter
currency_network_contract_name. If it's not set, the function will use the name
specified in the environment variable TRUSTLINES_CURRENCY_NETWORK_CONTRACT_NAME
or use the default "CurrencyNetwork".
This means, one can deploy the test contract by running
TRUSTLINES_CURRENCY_NETWORK_CONTRACT_NAME=TestCurrencyNetwork tl-deploy ...
> add a bit of infrastructure to test or call internal functions

- CHANGELOG.rst
- CONTRIBUTING.md
- contracts/Exchange.sol
- contracts/lib/Authorizable.sol
- contracts/lib/Destructable.sol
- contracts/lib/Ownable.sol
- contracts/lib/SafeMath.sol
- contracts/tokens/DummyToken.sol
- contracts/tokens/StandardToken.sol
- contracts/tokens/Token.sol
- py-bin/set_npm_version.sh
This is the result of running 'pre-commit run -a'. It removes trailing
whitespace and multiple empty lines at the end of the file.
> fix whitespace issues where our pre-commit hooks would complain

- .pre-commit-config.yaml
- CHANGELOG.rst
also remove flake8-invalid-escape-sequences, which isn't needed anymore with a
recent flake8.
> update pre-commit hooks to 2.0, disallow commits to develop branch

- tests/test_currency_network_basics.py
- tests/test_currency_network_interests.py
Otherwise we'll get tons of warnings when running the tests.
> use new way to call/transact on contracts

- contracts/CurrencyNetwork.sol
- contracts/Exchange.sol
- contracts/TestCurrencyNetwork.sol
- contracts/lib/Ownable.sol
This is the preferred way to implement a constructor and is mandatory for
solidity 0.5 or up.
See https://github.com/trustlines-network/contracts/issues/168
> use new constructor() syntax for constructors

- .circleci/config.yml
- Makefile
- py-bin/.npmignore
We need a .npmignore file now, because the py-bin directory might contain
various python build artifacts. We should move the npm related stuff to a
dedicated directory later.
> initial circleci config

- py-deploy/setup.py
I forgot to add the deploy tools as a dependency in setup.py.
> Add missing dependency of py-deploy

- .pre-commit-config.yaml
- .soliumrc.json
- contracts/Identity.sol
- contracts/tests/TestContract.sol
- contracts/tests/TestIdentity.sol
- py-deploy/tldeploy/identity.py
- tests/test_identity.py
Add methods to allow to validate a meta transaction
before sending it
Also send_meta_transaction now returns the hash of the
envelop transaction
> Add validation to delegator

- .gitattributes
Just skimmed through the contracts via github and noticed that syntax highlighting for solidity is not enabled.
> Add solidity syntax highligting in github

- .circleci/config.yml
- Dockerfile
- contracts/CurrencyNetwork.sol
- contracts/CurrencyNetworkInterface.sol
- contracts/Exchange.sol
- contracts/Identity.sol
- contracts/lib/Authorizable.sol
- contracts/lib/Destructable.sol
- contracts/lib/ECDSA.sol
- contracts/lib/Ownable.sol
- contracts/lib/SafeMath.sol
- contracts/lib/it_set_lib.sol
- contracts/tests/TestContract.sol
- contracts/tests/TestCurrencyNetwork.sol
- contracts/tests/TestIdentity.sol
- contracts/tokens/DummyToken.sol
- contracts/tokens/Receiver_Interface.sol
- contracts/tokens/StandardToken.sol
- contracts/tokens/Token.sol
- contracts/tokens/UnwETH.sol
- tests/test_gas_costs.py
I replaced `keccak256(a, b)` by `keccak256(abi.encodePacked(a, b))` as I believe it is the expected behaviour of not padding the data before hashing them (and keccak only takes one argument now).
I removed some getter functions that have the same name as a public variable as solc would throw an error saying there is two functions with the same name since it creates a public getter function for public parameters.
I use `address(uint160(owner))` to selfDestruct because it requires a payable address and owner is not payable.
> Upgrade the contracts to solidity 0.5.8

- .pre-commit-config.yaml
This includes an update for ethlint. The old version didn't check all
files.
> Update the pre-commit hooks

- contracts/CurrencyNetwork.sol
- tests/test_currency_network_onbaording.py
closes https://github.com/trustlines-protocol/contracts/issues/229
Adds onboarding rules. When owner uses `setAccount()` he is assumed as onboarding the users he sets the account for. This was asked for by Andreas.
> Add rules for user onBoarding accounting

- contracts/CurrencyNetwork.sol
- tests/test_close_trustline.py
- tests/test_currency_network_basics.py
- tests/test_currency_network_fees.py
- tests/test_currency_network_freezing.py
- tests/test_currency_network_interests.py
- tests/test_currency_network_onbaording.py
- tests/test_currency_network_receiver_pays.py
- tests/test_exchange.py
- tests/test_gas_costs.py
Change updateTrustlines and setAccount methods to be able to freeze trustlines
update tests to the new function signature
Will implement the fact that frozen TL are unusable in other PR.
related to: https://github.com/trustlines-protocol/contracts/issues/227
> Add isFrozen status to trustline agreements

- contracts/CurrencyNetwork.sol
- tests/test_information_from_events.py
closes: https://github.com/trustlines-protocol/contracts/issues/226
Check this and tell me if I need to improve it. The actual implementation for getting this information will be done differently on the relay server via db queries I assume, so i did not spend so much time on cleaning it.
> Add tests showing calculation for transfer information based on events

- contracts/CurrencyNetwork.sol
- py-deploy/tldeploy/cli.py
- tests/test_currency_network_freezing.py
This includes:
- extend currency network contract to allow disabling freezing on initialization
- disable freezing per default for deploy tool
Closes: trustlines-network/project#682
> Make expiration of currency networks optional

- .circleci/config.yml
With 'ethlint@>=1.2.5', we would automatically use a new version on
circleci if it becomes available.
Also see https://github.com/trustlines-protocol/contracts/pull/249 and
https://github.com/trustlines-protocol/contracts/pull/250
> Pin ethlint to 1.2.5 on circle ci

- constraints.txt
Related to: trustlines-network/project#703
> Update contract-deploy-tools version to 0.6.1

- contracts/CurrencyNetwork.sol
- contracts/tests/TestCurrencyNetwork.sol
- py-deploy/tldeploy/core.py
- tests/test_close_trustline.py
- tests/test_currency_network_basics.py
- tests/test_currency_network_erc165.py
- tests/test_currency_network_fees.py
- tests/test_currency_network_freezing.py
- tests/test_currency_network_interests.py
- tests/test_currency_network_onboarding.py
- tests/test_currency_network_receiver_pays.py
- tests/test_currency_network_registry.py
- tests/test_deploy.py
- tests/test_exchange.py
- tests/test_gas_costs.py
- tests/test_information_from_events.py
Also remove the accountManagement parameter now useless in the contract
closes https://github.com/trustlines-protocol/contracts/issues/261
> Move setAccount function back to TestCurrencyNetwork

- contracts/CurrencyNetwork.sol
- contracts/CurrencyNetworkMetaData.sol
We keep the currency network inteface as is since it is used
in the registry to define what a currency network should implement.
We could remove redundancy by changing the
CurrencyNetworkInterface to a contract and making it a
CurrencyNetworkMetaData but I do not think it is better.
> Split meta data from currency network

- contracts/CurrencyNetwork.sol
- tests/test_close_trustline.py
- tests/test_currency_network_interests.py
As transfer bigger than uint64 are not handled we should revert
triangulated transfer of such values
Also accept maxFees of uint64 in closeTrustlineByTriangulated...
> Prevent close trustline triangulated transfer overflow

- contracts/CurrencyNetwork.sol
- contracts/tests/TestCurrencyNetwork.sol
- tests/test_close_trustline.py
- tests/test_currency_network_basics.py
- tests/test_currency_network_debt.py
- tests/test_currency_network_fees.py
- tests/test_currency_network_freezing.py
- tests/test_currency_network_interests.py
- tests/test_currency_network_onboarding.py
- tests/test_currency_network_receiver_pays.py
- tests/test_exchange.py
- tests/test_gas_costs.py
- tests/test_information_from_events.py
The fee fields were originally planned to be used for onboarding
rewards.
This removal is a breaking change, as the number of fields returned by
getAccount will change.
> Remove unused outstanding fees fields

- Makefile
- contracts/identity/Identity.sol
- contracts/identity/IdentityProxyFactory.sol
- contracts/tests/TestContract.sol
- contracts/tests/TestIdentity.sol
- py-deploy/tldeploy/core.py
- py-deploy/tldeploy/identity.py
- tests/test_gas_costs.py
- tests/test_identity.py
- tests/test_identity_factory.py
I had to remove the `success` return value of `executeTransaction` because of stack too deep problem.
Breaks the interface of the identity contract so breaks the end2end tests.
closes: https://github.com/trustlines-protocol/contracts/issues/290
> Update signature of executeTransaction in identity for new features

- contracts/identity/Identity.sol
- tests/identity/test_identity.py
- tests/test_gas_costs.py
I considered that user of this function wants the regular ethereum tx flow and just revert and fail the outer transaction in case the inner tx fails. They can then check whether the outer tx failed if they want the status.
The other choice is letting the tx succeed and emit an event with the status to be closer to what `executeTransaction` does.
> Add function to execute a meta-tx from owner without signature

- contracts/identity/Identity.sol
- tests/identity/test_gas_costs_identity.py
Index the meta transaction hash in execution events
to be able to search for them more efficient.
> Index meta transaction hash in execution events

- CHANGELOG.rst
- py-deploy/setup.py
Need to release a new version to make https://github.com/trustlines-protocol/relay/pull/426 work.
> Changelog 1.1.1

- tests/currency_network/test_gas_costs_currency_network.py
The value from the test is used in the clientlib gas limit
> Add gas tests for canceling a trustline update

- py-deploy/tldeploy/identity.py
The warning came from web3 trying to process a receipt containing
events from multiple contracts with a spectific contract event
processor.
This could also be fixed by filtering the receipt before letting web3 process it, or finding another way to get the events arguments, but I do not think it is better.
closes https://github.com/trustlines-protocol/relay/issues/506
> Disable warning about unknown event seen when deploying identity

- CONTRIBUTING.md
- README.rst
- docs/deploy.md
I removed `deploy.md` because I think it is redundant with the `tl-deploy --help` documentation and was outdated.
How to release new versions not yet explained, I think you'd be writing that better than me @berndbohmeier
> Improve docs to match outline and be both simple and complete

- contracts/currency-network/CurrencyNetworkBasic.sol
- tests/currency_network/test_currency_network_basics.py
- tests/currency_network/test_currency_network_interests.py
- tests/currency_network/test_currency_network_onboarding.py
Currently we were just returning without changing the trustline when an
attempt was made to change the trustlines from all zero to all zero.
This worked fine, but meant that you would not get an event and not a
failed transaction, which would mean no user feedback on what happend.
This now will instead revert, so giving a user feedback that this is not
possible.
> Change to revert when attempting zero tl update

- CHANGELOG.rst
- Makefile
- py-bin/README.md
- py-bin/setup.py
- py-bin/tlbin/__init__.py
- py-bin/tlbin/contracts.py
- py-deploy/tldeploy/core.py
This package installed in editable mode by make enable the feature
that running `make compile` will provide the newly compiled contracts
to tldeploy that uses tlbin to load the contracts.
> Add package tlbin to load contracts.json

- py-bin/setup.py
- py-deploy/setup.py
- py-deploy/tldeploy/core.py
Revert the changes of pydeploy to make it compatible again with
old version of pybin
> Fix the setup.py by adding missing long_description_content_type

- .circleci/config.yml
It seems twine is not up to date on the builder and that makes uploading the dists fail.
https://app.circleci.com/pipelines/github/trustlines-protocol/contracts/453/workflows/b2c3597c-45b2-412b-9c19-12eb8b330fd4/jobs/4079
https://stackoverflow.com/questions/49806586/twine-upload-typeerror-expected-string-or-bytes-like-object
> Add command to upgrade twince in cicrcleci config

- .gitignore
- Makefile
- py-bin/index.js
- py-bin/setup.py
- py-bin/tlbin/contracts.py
This makes it so that you can load the contracts.json even when py-bin is installed in editable mode.
If you install it in editable mode, the data files that should be copied with `data_files=[("trustlines-contracts/build", ["tlbin/contracts.json"])]` are not copied (because that's the stupid way it works). And then the loader cannot find the `contracts.json` to load.
Now the contracts will be packed right next to `contracts.py` thanks to `package_data={"tlbin": ["contracts.json"]}`.
I keep the previous way of packing the contracts for backward compatibility.
> Fix packing of contracts.json in py-bin

- py-bin/package.json
By default scoped packages have privite visibility, which was preventing us from publishing on npm.
> Fix publishing to npm

- CHANGELOG.rst
- contracts/currency-network/CurrencyNetworkBasic.sol
Previously the new balance was restricted by min/max balance
but should be restricted by old balance instead to prevent that
negative interest rates actually result in a growing balance
> Restrict balance with negative interests to old balance

- .gitignore
- Makefile
- py-bin/README.md
- py-bin/scripts/merge_abis.py
- py-bin/setup.py
- py-bin/tlbin/__init__.py
- py-bin/tlbin/contracts.py
- py-bin/tlbin/legacy_currency_networks.json
- py-deploy/tldeploy/cli.py
tlbin now provides a merged abi package data file and a function
to load the abi of all versions of currency networks.
Pins the version of legacy currency networks abi.
This is useful for example for eth-index to figure out the abi
to decode events from currency network proxies that got upgraded
> Provide abi of all versions of currency networks merged together

- contracts/currency-network/version3/CurrencyNetworkV3.sol
Currently our identity calls the increaseDebt function when we call executeTransaction. This cannot work with gnosisSafe, but it appears that there is a workaround.
https://github.com/safe-global/safe-contracts/blob/da66b45ec87d2fb6da7dfd837b29eacdb9a604c5/contracts/common/SecuredTokenTransfer.sol
We could use a gasToken and increase the debt toward the delegate. Kind of hacky, but seems better than having to do a multi send for this.
> Trick gnosis safe to work with our debt tracking
