.gitignore
contracts/CurrencyNetwork.sol
contracts/CurrencyNetworkFactory.sol
contracts/EternalStorage.sol
contracts/Fees.sol
contracts/ICurrencyNetwork.sol
contracts/Interests.sol
contracts/Migrations.sol
contracts/Trustline.sol
contracts/gov/GovernanceTemplate.sol
contracts/lib/ECVerify.sol
contracts/lib/NameAddressLibrary.sol
contracts/lib/Owned.sol
contracts/lib/SafeMath.sol
contracts/lib/it_set_lib.sol
contracts/lib/registry.sol
contracts/user/IdentityFactory.sol
contracts/user/IdentityFactoryWithRecoveryKey.sol
contracts/user/Proxy.sol
contracts/user/RecoverableController.sol
contracts/user/RecoveryQuorum.sol

Add a gitignore file
Change required solidity versions
Add BalanceUpdate again for now

change requiered solidity version and add BalanceUpdate

---

.soliumrc.json
.travis.yml
contracts/CurrencyNetwork.sol
contracts/CurrencyNetworkFactory.sol
contracts/lib/ECVerify.sol
contracts/lib/ERC223_Token.sol
tlcontracts/deploy.py

add order of function as a linter rule
make naming an error
fixes #58

Add linter rules

---

contracts/CurrencyNetwork.sol
tests/test_currency_network_basics.py

Add functions for trustline update workflow

---

contracts/CurrencyNetwork.sol
tests/test_currency_network_basics.py

the origin of the trustline update is now the initiator of the proposal

Fix the origin of the trustline update

---

.travis.yml

setuptools_scm doesn't work otherwise.

travis: don't use shallow clone

---

constraints.txt
py-deploy/setup.py

I forgot to update the dependencies

Update tl-bin dependency to new version

---

py-deploy/tldeploy/cli.py

Before it was not possible to deploy a network with 0 fees

Allow setting zero fees while deploying

---

.gitignore
.travis.yml
py-bin/index.js
py-bin/package.json

This adds an npm package that contains the smart contracts abi. Still
missing are the proper log settings for npm.
Closes #47

Add publishing of abi to npm

---

contracts/TestCurrencyNetwork.sol

let me export transfer related data as test data.

enhance test contract with transfer related methods

---

constraints.txt
contracts/CurrencyNetwork.sol
py-deploy/tldeploy/core.py
requirements.txt
tests/conftest.py
tests/test_close_trustline.py
tests/test_currency_network_basics.py
tests/test_currency_network_fees.py
tests/test_currency_network_interests.py
tests/test_currency_network_receiver_pays.py
tests/test_exchange.py
tests/test_gas_costs.py
tests/test_signing.py

Use the new pytest plugin of the tools package and remove the now
unecessary code.

Use pytest plugin of deploy tools package

---

contracts/Identity.sol
py-deploy/tldeploy/identity.py
tests/test_identity.py

Implement nonce mechanism for increasing nonce but keep the old
behavior for nonce=0
Closes #180

Implement nonce mechanism for meta transactions

---

py-deploy/tldeploy/core.py
tests/test_gas_costs.py
tests/test_identity.py

Add a function to deploy a new identity contract
Also add a gas cost test. The cost of deploying a identity is pretty
high at the moment.

Add deploy identity function

---

CHANGELOG.rst

we all already miss some new functionality, so let's make a new release.

update change log for 0.6.1

---

py-deploy/tldeploy/identity.py
tests/test_identity.py

Add a function to query the nonce so that the delegator can provided to
some one who wants to use his service

Add get nonce function to delegator

---

.circleci/config.yml
contracts/CurrencyNetwork.sol
contracts/Exchange.sol
contracts/Identity.sol
contracts/tests/TestCurrencyNetwork.sol

The command to check linting is still `solium --dir ...` and `ethling --dir ...` does not exist.
related: https://github.com/trustlines-network/contracts/issues/188

Change the install of solium to ethlint

---

run-docker-smoketest

stable is broken at the moment.

pin parity version

---

.pre-commit-config.yaml

The old solution did run solium with the --dir option. The new one only checks
changed files.

use ethlint-pre-commit

---

contracts/CurrencyNetwork.sol
tests/test_currency_network_interests.py

Add missing BalanceUpdate on trustline change

---

contracts/CurrencyNetwork.sol
py-deploy/tldeploy/cli.py
py-deploy/tldeploy/core.py
tests/conftest.py
tests/test_close_trustline.py
tests/test_currency_network_basics.py
tests/test_currency_network_fees.py
tests/test_currency_network_freezing.py
tests/test_currency_network_interests.py
tests/test_currency_network_receiver_pays.py
tests/test_deploy.py
tests/test_exchange.py
tests/test_gas_costs.py
tests/test_identity.py

Closes https://github.com/trustlines-protocol/contracts/issues/221
Does not add feature, just split task for smaller PRs

Add expirationTime to currency networks and function to freeze them

---

CHANGELOG.rst
py-deploy/setup.py

Also update requirements of tldeploy to sue contracts-bi 0.9.0

Update changelog for version 0.9.0

---

.pre-commit-config.yaml
mypy.ini

that hopefully fixes the problems you had with mypy.

Fix pre-commit's mypy configuration

---

py-deploy/tldeploy/cli.py
py-deploy/tldeploy/core.py
py-deploy/tldeploy/identity.py
tests/test_exchange.py
tests/test_unweth.py

Integrate recent features of deploy tools

---

contracts/CurrencyNetworkRegistry.sol
tests/test_currency_network_registry.py

Closes: trustlines-network/project#646

Throw event each time a currency network gets add

---

contracts/CurrencyNetwork.sol

closes https://github.com/trustlines-protocol/contracts/issues/269

Add NetworkFreeze event

---

CHANGELOG.rst
contracts/CurrencyNetwork.sol
contracts/CurrencyNetworkInterface.sol
contracts/Exchange.sol
contracts/tests/TestCurrencyNetwork.sol
tests/test_currency_network_basics.py
tests/test_currency_network_onboarding.py

Remove destructable
Remove ownable
Remove boolean return values

First set of clean ups

---

contracts/CurrencyNetwork.sol
tests/test_currency_network_basics.py

Only initiator of request can cancel it

Add function to cancel trustline updates requests

---

tests/conftest.py
tests/test_close_trustline.py
tests/test_currency_network_basics.py
tests/test_currency_network_debt.py
tests/test_currency_network_fees.py
tests/test_currency_network_freezing.py

WIP Use currency network adapter
Add a test adapter for the currency network to make the test easiert to
understand and easier to maintain.

Currency network test adapter

---

README.rst
docs/deploy.md

Add sections on how to deploy identity contracts.

Update deploy docs

---

README.rst

Adjust installation docs for libsecp256k1 library

---

CONTRIBUTING.md
README.rst

Add badges, contributing, and release guideline to readme

---

contracts/currency-network/CurrencyNetworkBasic.sol

close https://github.com/trustlines-protocol/contracts/issues/320

Remove unsused acceptId function in currency network basic

---

contracts/currency-network/CurrencyNetworkBasic.sol
contracts/currency-network/CurrencyNetworkInterface.sol
contracts/currency-network/CurrencyNetworkRegistry.sol
contracts/currency-network/CurrencyNetworkSafeMath.sol
contracts/currency-network/DebtTracking.sol
contracts/identity/Identity.sol

close https://github.com/trustlines-protocol/contracts/issues/52

Update natspec that was missing for some functions

---

CHANGELOG.rst
py-deploy/tldeploy/cli.py
py-deploy/tldeploy/core.py

Outputs something like: 
`{"0x8a0d1D133dD0fAF7aad22b553a40666c4Cc55aBD": "0x385e2f29c74c9e24Cf80D7DfC24CfeAFe750be18", "0xD0d116522dD3EF0B04011e435B24C2B06d48c388": "0x0F4f5Af3A6f072A8A38dBbd7a81523C9Cf878df0"}`

Output a json file with mapping from old to new network in migration

---

py-deploy/tldeploy/cli.py
py-deploy/tldeploy/core.py

Also add method to unfreeze a network and remove its owner

Add cli methods to deploy new currency network proxies

---

.circleci/config.yml
dev-requirements.txt
py-deploy/requirements.txt
pyproject.toml

Use python3.8 in builders for circleci
